---
- name: install pip dependencies for running the unit and functional tests
  pip: requirements="{{ test_pip_requirements }}"

- name: install testing deb pkg dependencies
  apt: name="{{ item }}" state=latest
  with_items: test_apt_dependencies

# Selenium 3 makes breaking changes with the 2.X API, and requires the
# installation of the Mozilla geckodriver. Since the Aaron Swartz Day Hackathon
# is approaching, which will involve many new external contributors, we've
# decided to play it as safe as possible by downgrading Firefox to the latest
# version (46.0.1) that is compatible with the last 2.X series Selenium release
# (2.53.6). After the Hackathon, we'll resolve the geckodriver business and
# remove the following three tasks (as well as add firefox back to the
# `test_apt_dependencies` list).
- name: Download Firefox 46.0.1 for compatibility with Selenium 2.53.6.
  sudo: no
  get_url:
    # Since the whole tasklisk is run as root, the ansible_env.HOME fact is
    # /root. Since this command doesn't need to be run as root and is part of a
    # crutch anyway, I've just hardcoded /home/vagrant.
    dest: /home/vagrant/
    url: http://security.ubuntu.com/ubuntu/pool/main/f/firefox/firefox-locale-en_45.0.2+build1-0ubuntu1_amd64.deb
  tags:
    - apt

- name: Install dependencies for Firefox 46.0.1.
  apt:
    name: "{{ item }}"
  with_items:
    - libasound2
    - libcairo-gobject2
    - libgtk-3-0
    - libstartup-notification0
  tags:
    - apt

- name: Install Firefox 46.0.1 for compatibility with Selenium 2.53.6.
  apt:
    deb: /home/vagrant/firefox-locale-en_45.0.2+build1-0ubuntu1_amd64.deb
  tags:
    - apt

- name: Copy xvfb init script.
  copy:
    src: xvfb
    dest: /etc/init.d/xvfb
    owner: root
    mode: '700'
  tags:
    - xvfb
    - permissions

- name: update rc.d to run xvfb at boot
  command: "update-rc.d xvfb defaults"
  notify: start xvfb

- name: set DISPLAY environment variable for xvfb on reboot
  copy: src=xvfb_display.sh dest=/etc/profile.d/xvfb_display.sh owner=root mode=444
