---
- name: Update apt package lists.
  apt:
      update_cache: yes
  tags:
    - apt
    - development

- name: Install apt package dependencies for Development environment.
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: development_dependencies
  tags:
    - apt
    - development

- name: Install pip dependencies for SecureDrop.
  pip:
    requirements: "{{ securedrop_pip_requirements }}"
  tags:
    - pip
    - development

- name: Install sass Ruby gem
  gem:
    name: sass
    version: '3.4.22'
    state: present
    user_install: no
  sudo: yes
  tags:
    - development

# necessary for automated tests
- name: Compile sass to css
  shell: sass --update sass:static/css
  args:
    chdir: '{{ securedrop_repo  }}/securedrop'
#  register: sass_compile_result
#  changed_when: sass_compile_result.stdout != ''

# TODO: Probably better to set this env var in /etc/profile.d,
# since it doesn't need to be set ONLY for the securedrop user.
# Warrants further testing (e.g. Travis CI?), so leaving for now.
- name: Set SECUREDROP_ENV in bashrc.
  lineinfile:
    dest: /home/{{ securedrop_user }}/.bashrc
    state: present
    insertafter: EOF
    line: "export SECUREDROP_ENV=dev"
  tags:
    - environment
    - development
